Repository wakeup0105/Backend, pull requests merged in 2024-07, with the labels that each got.

#2 [Setting] 프로젝트 및 gitflow setting
  .github/pull_request_template.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/hackerton/wakeup/WakeupApplication.java
  src/test/java/hackerton/wakeup/WakeupApplicationTests.java
Labels: chore, setting

#4 [FEATURE] Member Entity 생성
  src/main/java/hackerton/wakeup/member/entity/Member.java
Labels: feature

#6 [FEATURE] 이메일 인증 적용 전 회원가입 로직 구현
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/JoinRequestDTO.java
  src/main/java/hackerton/wakeup/member/repository/MemberRepository.java
  src/main/java/hackerton/wakeup/member/service/MemberService.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
Labels: feature

#8 [FEATURE] 이메일 인증 기능 개발
  build.gradle
  src/main/java/hackerton/wakeup/email/service/EmailSenderService.java
  src/main/java/hackerton/wakeup/email/service/EmailSenderServiceImpl.java
  src/main/java/hackerton/wakeup/email/service/EmailVerifyService.java
  src/main/java/hackerton/wakeup/email/service/EmailVerifyServiceImpl.java
  src/test/java/hackerton/wakeup/email/service/EmailVerifyServiceImplTest.java
Labels: feature, setting

#10 [FEATURE] 이메일인증 회원가입 개발
  src/main/java/hackerton/wakeup/email/service/EmailVerifyServiceImpl.java
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/Member.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/JoinRequestDTO.java
  src/main/java/hackerton/wakeup/member/service/MemberService.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
Labels: feature

#12 [FEATURE] CORS 기본설정
  src/main/java/hackerton/wakeup/common/config/WebConfig.java
Labels: feature

#14 [FEATURE] 로그인 기능 개발
  build.gradle
  src/main/java/hackerton/wakeup/common/security/JwtTokenFilter.java
  src/main/java/hackerton/wakeup/common/security/JwtTokenUtil.java
  src/main/java/hackerton/wakeup/common/security/PasswordConfig.java
  src/main/java/hackerton/wakeup/common/security/SecurityConfig.java
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/LoginRequestDTO.java
  src/main/java/hackerton/wakeup/member/service/MemberService.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
Labels: feature

#20 [FEATURE] MemberInfo Entity 작성
  src/main/java/hackerton/wakeup/common/security/SecurityConfig.java
  src/main/java/hackerton/wakeup/member/entity/Member.java
  src/main/java/hackerton/wakeup/memberInfo/entity/MemberInfo.java
  src/main/java/hackerton/wakeup/memberInfo/entity/MemberInfoId.java
Labels: feature

#22 [FEATURE] 계정찾기 기능 구현
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/ChangePasswordRequestDTO.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/FindAccountRequestDTO.java
  src/main/java/hackerton/wakeup/member/service/MemberService.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
Labels: feature

#24 [FEATURE] 닉네임 설정 구현
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/Member.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
  src/main/java/hackerton/wakeup/memberInfo/controller/MemberInfoController.java
  src/main/java/hackerton/wakeup/memberInfo/entity/MemberInfo.java
  src/main/java/hackerton/wakeup/memberInfo/entity/MemberInfoId.java
  src/main/java/hackerton/wakeup/memberInfo/entity/dto/request/SetNicknameRequestDTO.java
  src/main/java/hackerton/wakeup/memberInfo/repository/MemberInfoRepository.java
  src/main/java/hackerton/wakeup/memberInfo/service/MemberInfoService.java
  src/main/java/hackerton/wakeup/memberInfo/service/MemberInfoServiceImpl.java
Labels: feature

#28 [FEATURE] 나의 정보 관리 페이지 기능 개발
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/dto/request/ChangePasswordRequestDTO.java
  src/main/java/hackerton/wakeup/member/entity/dto/response/MyInfoResponseDTO.java
  src/main/java/hackerton/wakeup/member/service/MemberService.java
  src/main/java/hackerton/wakeup/member/service/MemberServiceImpl.java
Labels: feature

#29 [FEATURE] Character Entity 생성 및 조회
  src/main/java/hackerton/wakeup/character/controller/CharacterController.java
  src/main/java/hackerton/wakeup/character/entity/Character.java
  src/main/java/hackerton/wakeup/character/entity/CharacterId.java
  src/main/java/hackerton/wakeup/character/entity/dto/response/CustomizeResponseDTO.java
  src/main/java/hackerton/wakeup/character/entity/dto/response/GrowResponseDTO.java
  src/main/java/hackerton/wakeup/character/repository/CharacterRepository.java
  src/main/java/hackerton/wakeup/character/service/CharacterService.java
  src/main/java/hackerton/wakeup/character/service/CharacterServiceImpl.java
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/Member.java
Labels: feature

#31 [FEATURE] JWT 토큰 반환형태 변경
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/member/entity/dto/response/JwtTokenResponseDTO.java
Labels: feature

#33 [FEATURE] 커스터마이징 Entity들 기능 생성
  src/main/java/hackerton/wakeup/body/own/controller/OwnBodyAvatarController.java
  src/main/java/hackerton/wakeup/body/own/entity/OwnBodyAvatar.java
  src/main/java/hackerton/wakeup/body/own/entity/dto/OwnBodyDtoConverter.java
  src/main/java/hackerton/wakeup/body/own/entity/dto/response/AllOwnBodyResponseDTO.java
  src/main/java/hackerton/wakeup/body/own/repository/OwnBodyAvatarRepository.java
  src/main/java/hackerton/wakeup/body/own/service/OwnBodyAvatarService.java
  src/main/java/hackerton/wakeup/body/own/service/OwnBodyAvatarServiceImpl.java
  src/main/java/hackerton/wakeup/body/part/entity/Body.java
  src/main/java/hackerton/wakeup/character/entity/Character.java
  src/main/java/hackerton/wakeup/eyes/own/controller/OwnEyesAvatarController.java
  src/main/java/hackerton/wakeup/eyes/own/entity/OwnEyesAvatar.java
  src/main/java/hackerton/wakeup/eyes/own/entity/dto/OwnEyesDtoConverter.java
  src/main/java/hackerton/wakeup/eyes/own/entity/dto/response/AllOwnEyesResponseDTO.java
  src/main/java/hackerton/wakeup/eyes/own/repository/OwnEyesAvatarRepository.java
  src/main/java/hackerton/wakeup/eyes/own/service/OwnEyesAvatarService.java
  src/main/java/hackerton/wakeup/eyes/own/service/OwnEyesAvatarServiceImpl.java
  src/main/java/hackerton/wakeup/eyes/part/entity/Eyes.java
  src/main/java/hackerton/wakeup/head/own/controller/OwnHeadAvatarController.java
  src/main/java/hackerton/wakeup/head/own/entity/OwnHeadAvatar.java
  src/main/java/hackerton/wakeup/head/own/entity/dto/OwnHeadDtoConverter.java
  src/main/java/hackerton/wakeup/head/own/entity/dto/response/AllOwnHeadResponseDTO.java
  src/main/java/hackerton/wakeup/head/own/repository/OwnHeadAvatarRepository.java
  src/main/java/hackerton/wakeup/head/own/service/OwnHeadAvatarService.java
  src/main/java/hackerton/wakeup/head/own/service/OwnHeadAvatarServiceImpl.java
  src/main/java/hackerton/wakeup/head/part/entity/Head.java
  src/main/java/hackerton/wakeup/mouth/own/controller/OwnMouthAvatarController.java
  src/main/java/hackerton/wakeup/mouth/own/entity/OwnMouthAvatar.java
  src/main/java/hackerton/wakeup/mouth/own/entity/dto/OwnMouthDtoConverter.java
  src/main/java/hackerton/wakeup/mouth/own/entity/dto/response/AllOwnMouthResponseDTO.java
  src/main/java/hackerton/wakeup/mouth/own/repository/OwnMouthAvatarRepository.java
  src/main/java/hackerton/wakeup/mouth/own/service/OwnMouthAvatarService.java
  src/main/java/hackerton/wakeup/mouth/own/service/OwnMouthAvatarServiceImpl.java
  src/main/java/hackerton/wakeup/mouth/part/entity/Mouth.java
Labels: feature
