Repository wakeup0105/Backend, pull requests merged in 2024-08, with the labels that each got.

#39 [REFACTOR] PUT 요청 -> PATCH로 변경
  src/main/java/hackerton/wakeup/member/controller/MemberController.java
  src/main/java/hackerton/wakeup/memberInfo/controller/MemberInfoController.java
Labels: refactor

#47 17 feature 채팅 기능 개발을 위한 엔터티 작성
  .gitignore
  src/main/java/hackerton/wakeup/chat/domain/Background.java
  src/main/java/hackerton/wakeup/chat/domain/ChatRoom.java
  src/main/java/hackerton/wakeup/chat/domain/Status.java
Labels: feature

#48 Feature: Notification 엔터티 작성
  src/main/java/hackerton/wakeup/notification/domain/Notification.java
Labels: feature

#49 [Feature] Swagger 설정 및 테스트
  src/main/java/hackerton/wakeup/common/config/SwaggerConfig.java
  src/main/java/hackerton/wakeup/common/domain/BaseEntity.java
  src/main/java/hackerton/wakeup/common/security/SecurityConfig.java
Labels: feature, setting

#56 [REFACTOR] Spring Security FilterChain 수정
  src/main/java/hackerton/wakeup/common/security/SecurityConfig.java
Labels: refactor

#58 [BUG] cors method 전체 허용
  src/main/java/hackerton/wakeup/common/config/WebConfig.java
Labels: bug
